# Generated by Django 3.0.8 on 2021-01-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210108_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=0, max_length=250, unique_for_date='publish'),
            preserve_default=False,
        ),
    ]
